### ISSUE TITLE
不透明度が変化しない

### ISSUE THREAD

**Issue by seon3217** [tanbatu/comment-zouryou#10]
不透明度が変化しません。
ブラウザ　Chrome バージョン: 108.0.5359.125（Official Build） （64 ビット）
ニコニコの視聴方法はhttpを選択。ハードウェアアクセラレーションはオン（関係あるかわからんけど）。
それ以外の描画設定の項目は反映されている様子。

**Comment by xpadev-net** [comment]
修正したので画像の赤丸のところからダウンロードしてもらえれば動作すると思います
![Screenshot 2022-12-23 at 23-29-34 tanbatu_comment-zouryou](https://user-images.githubusercontent.com/96982836/209352142-62f0dca3-52e4-4da9-b6b4-c314bd3269fe.png)
※PiPについては諸事情により透明度が機能しません

**Comment by seon3217** [comment]
迅速な対応助かりますm(._.)m
ありがとうございました
