### ISSUE TITLE
Endless loop in replace script

### ISSUE THREAD

**Issue by DeltaFlyerW** [tanbatu/comment-zouryou#12]
![image](https://user-images.githubusercontent.com/48078918/220124540-46d0064b-25be-4638-9e8b-0ebfae679023.png)

https://www.nicovideo.jp/watch/sm27429088

**Comment by xpadev-net** [comment]
@DeltaFlyerW 
Thanks for the report.
This is an implementation error on my [niconicomments](https://github.com/xpadev-net/niconicomments/) side and I will take care of it.
-> [[不具合][全般]@置換で無限ループが発生する](https://github.com/xpadev-net/niconicomments/issues/40)
