### ISSUE TITLE
コメントが一切表示されない

### ISSUE THREAD

**Issue by SeruranBlue** [tanbatu/comment-zouryou#15]
- Chromeウェブストア および githubリリースどちらでも発生
※ところで、githubのリリースではv4.0となっているのに、それを読み込むと"3.2"と表示される

Windows 10
Chrome  111.0.5563.147（Official Build） （64 ビット）

**Comment by SeruranBlue** [comment]
![image](https://user-images.githubusercontent.com/121824800/229397196-25f99667-3016-40ff-8cf4-7f8f1af0833d.png)

こんなエラーが出てました:(Github V4.0版)
![image](https://user-images.githubusercontent.com/121824800/229397250-dc18520b-7446-4b03-9034-54eaf8012391.png)

Chromeウェブストアではエラーが出ないが、やはり表示されない

**Comment by xpadev-net** [comment]
@SeruranBlue 報告ありがとうございます

スクリーンショットを見る限りぼざろの1話(so41178183)かなと思い確認してみましたがこちらでは確認できなかったため、
- 発生する動画ID(特定の動画のみなのか、すべての動画でなのか)
- hls・http両方で発生するか

を教えて下さい

また、併用している拡張機能があれば一度全てを無効にして試してみてください

**Comment by SeruranBlue** [comment]
返信が遅くなりました。
いろいろと調べた所、Video Speed Controllerと競合が発生しているようで、それを無効にすることで実行できました。
(https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk?hl=ja)

**Comment by SeruranBlue** [comment]
![image](https://user-images.githubusercontent.com/121824800/229625196-83c0919b-32dd-4873-83cf-be0f1a3f4ad0.png)
