### ISSUE TITLE
機能についての要望

### ISSUE THREAD

**Issue by Hayao0819** [tanbatu/comment-zouryou#16]
拡張機能ありがたく使わせていただいています。

いくつか追加して欲しい機能があるので提案させていただきます。

- [ ] 設定保存 - 入力した倍数の保存
- [ ] コメントの自動読み込み

**Comment by tanbatu** [comment]
返信が遅れて申し訳ありません。

提案いただいた機能は実装可能ですが、自動読み込みに関してはAPI制限の制約があるため、上限を設けて実装することになるかもしれません。ご了承いただければと思います。

早急に更新します。

**Comment by Hayao0819** [comment]
ありがとうございます。よろしくお願いします。

**Comment by tanbatu** [comment]
[v5.0](https://github.com/tanbatu/comment-zouryou/releases/tag/release5)
機能を追加致しました。

**Comment by Hayao0819** [comment]
ありがとうございます！！
