### ISSUE TITLE
非ログイン下で読み込みが完了しない

### ISSUE THREAD

**Issue by yui10** [tanbatu/comment-zouryou#20]
拡張機能を使用させて頂いている中で、機能しなくなった場合がありましたので報告致します。
再現できる不具合か分からないため無駄になってしまうかもしれませんが、簡単に原因となり得そうな所も探していたため参考にして頂ければ幸いです。

# バグの内容 
非ログイン時にコメントを読み込もうとするとエラーが発生して処理が終了しない。
そのためリロードしないとコメントリストや動画リストが開けなくなる。

![image](https://github.com/tanbatu/comment-zouryou/assets/79691301/7dd3c2bd-dfbb-4773-9949-6e1942c866b7)

# 原因と思われる部分

1.  APIサーバの仕様が変更されたことで非ログインの状態では過去のコメントへのアクセスができなくなっている(https://nvcomment.nicovideo.jp/v1/threads へのレスポンスは"INVALID_TOKEN"が帰って来ている)
2. 上記サーバで取得できない場合は旧APIサーバ(https://flapi.nicovideo.jp/api/getthreadkey?thread=) を使用しているが、 [停止](https://blog.nicovideo.jp/niconews/182541.html) しているため、404 Not Foundで取得できていない
3. 旧APIサーバへのfetchでエラーが発生している

![image](https://github.com/tanbatu/comment-zouryou/assets/79691301/cdeb5299-5437-4cf0-907a-1ca7ef3eafd7)

# 対応例
- ログインするように促す文言・画面を追加する
- 取得できない場合は失敗したことを表示し元の画面に遷移する
- 非ログイン時はニコニコ公式がコメントを取得しているときと同様に取得する(このコミットの[index.js](https://github.com/tanbatu/comment-zouryou/blob/64464e96f85c652e338eb5c936832c278f28dace/index.js#L117)だと117・118行目を消す。この場合通常のコメント量と同じになる可能性がある)

**Comment by tanbatu** [comment]
報告ありがとうございます！恐らく旧コメントAPIが停止したことが原因かと思われるので、
ログインを促すように変更したいと思います。

**Comment by yui10** [comment]
対応ありがとうございます!!
