### ISSUE TITLE
ある程度コメントが少ない動画でコメント増量を使用すると、動画が終了する寸前ですべて"Undefined"になる。

### ISSUE THREAD

**Issue by SeruranBlue** [tanbatu/comment-zouryou#22]
![image](https://github.com/tanbatu/comment-zouryou/assets/121824800/c7e8d6c4-811a-439b-8886-603f1ecf13c1)
(sm43080490)

**Comment by tanbatu** [comment]
d9521d088f2765dbb9b3975a30d0bf1870267317
大変お待たせしました。修正致しました。

**Comment by SeruranBlue** [comment]
連絡が遅くなりました
ありがとうございます。
