### ISSUE TITLE
[バグ]非プレミアム会員下(非ログイン)で発生するバグ

### ISSUE THREAD

**Issue by Negima1072** [tanbatu/comment-zouryou#7]
- 再生前にコメントを読み込むと広告の再生中にすでにコメントが描写されてしまう
~- 読み込み後初期状態のままコメントが再生されない~

他にもあるかもしれない...?

以上のバグはプレミアム会員下だと確認できませんでした。
確認動画：
- https://www.nicovideo.jp/watch/sm35919998
- https://www.nicovideo.jp/watch/sm9
※低倍率でも確認しています。

**Comment by xpadev-net** [comment]
>読み込み後初期状態のままコメントが再生されない

これ多分 #5 と一緒だと思います

**Comment by Negima1072** [comment]
> > 読み込み後初期状態のままコメントが再生されない
> 
> これ多分 #5 と一緒だと思います

お、PR反映させたら解決しました👍
